FROM node:18-alpine

WORKDIR /app

COPY package*.json /app
COPY prisma ./prisma/ 

RUN npm install --omit=dev && npm cache clean --force
RUN npx prisma generate

COPY . .

EXPOSE ${PORT}

# RUN npm run build

# CMD ["npm", "run", "start:migrate:dev"]