version: '4.16.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 4001:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PORT: 32768
      POSTGRES_HOST: host.docker.internal
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - app-network
    working_dir: /app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
